# Open edX services
version: "3"
services:
  flower:
    image: derex/openedx-ironwood:latest
    command:
      sh -c 'pip install flower;
        flower --port=5555
        --broker=$$(python -c "from django.conf import settings; print(settings.BROKER_URL)")'
    ports:
      - 127.0.0.1:5555:5555
    container_name: derex_flower

  lms:
    image: derex/openedx-ironwood:latest
    command:
      sh -c 'gunicorn --name $${SERVICE_VARIANT}
        --bind=0.0.0.0:4700
        --max-requests=1000
        wsgi:application'
    volumes:
      - derex_ironwood_data:/openedx/data/
    ports:
      - 127.0.0.1:4700:4700
    container_name: derex_lms

  cms:
    image: derex/openedx-ironwood:latest
    command:
      sh -c 'gunicorn --name $${SERVICE_VARIANT}
        --bind=0.0.0.0:4800
        --max-requests=1000
        wsgi:application'
    volumes:
      - derex_ironwood_data:/openedx/data/
    environment:
      SERVICE_VARIANT: cms
    ports:
      - 127.0.0.1:4800:4800
    container_name: derex_cms

  lms_worker:
    image: derex/openedx-ironwood:latest
    command:
      sh -c './manage.py $${SERVICE_VARIANT}
        celery worker --loglevel=info
        --hostname=edx.$${SERVICE_VARIANT}.core.default
        --maxtasksperchild 100'
    container_name: derex_lms_worker
    volumes:
      - derex_ironwood_data:/openedx/data/
    environment:
      C_FORCE_ROOT: "True"

  cms_worker:
    image: derex/openedx-ironwood:latest
    command:
      sh -c './manage.py $${SERVICE_VARIANT}
        celery worker --loglevel=info
        --hostname=edx.$${SERVICE_VARIANT}.core.default
        --maxtasksperchild 100'
    container_name: derex_cms_worker
    volumes:
      - derex_ironwood_data:/openedx/data/
    environment:
      C_FORCE_ROOT: "True"
      SERVICE_VARIANT: cms

networks:
  default:
    external:
      name: derex

volumes:
  derex_ironwood_data:
