# Services needed for Open edX to work
version: "3"
services:
  mongodb:
    image: mongo:3.2.21
    container_name: mongodb
    command:
      mongod --smallfiles --nojournal
        --storageEngine wiredTiger
        --wiredTigerEngineConfigString="cache_size=${MONGO_CACHE_MB:-200}M"
    volumes:
      - derex_mongodb:/data/db

  mysql:
    image: mysql:5.6.36
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - derex_mysql:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.5.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=openedx"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - derex_elasticsearch:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3.6.16-alpine
    container_name: rabbitmq
    volumes:
      - derex_rabbitmq:/var/lib/rabbitmq

  mailslurper:
    image: marcopas/docker-mailslurper
    # Something needs to prime this with
    # docker-compose --project-name derex -f derex/runner/compose_files/services.yml exec mysql /usr/bin/mysql -psecret -e "$(cat derex/runner/fixtures/mailslurper.sql)"
    container_name: smtp
    ports:
      - 127.0.0.1:4300:4300
      - 127.0.0.1:4301:4301
    volumes:
      - ./../fixtures/mailslurper.json:/opt/mailslurper/config.json
    depends_on:
      - mysql

volumes:
  derex_mongodb:
    external: true
  derex_mysql:
    external: true
  derex_elasticsearch:
    external: true
  derex_rabbitmq:
    external: true

networks:
  default:
    external:
      name: derex
