repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: check-yaml
  - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'
    hooks:
    -   id: mypy
        args:
        - --ignore-missing-imports

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
