exclude: derex/runner/compose_files/openedx_customizations/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: debug-statements
      - id: check-added-large-files
        exclude: "^\
          examples/.*/complete/themes/.*/lms/static/css/.*\
          $"
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: check-yaml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--per-file-ignores=\
            docker-definition/derex_django/derex_django/settings/default/*.py,\
            derex/runner/compose_files/openedx_customizations/*\
            :F821,F405,F403,E266"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args:
          ["--install-types", "--non-interactive", "--ignore-missing-imports"]
        exclude: "^\
          examples/.*|\
          docker-definition/derex_django/derex_django/settings/default/.*|\
          docker-definition/derex_django/setup.py\
          $"

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        exclude: docs/html_templates/layout.html
