repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    exclude: .bumpversion.cfg
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: .bumpversion.cfg
  - id: check-yaml
  - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
        args:
        - --ignore-missing-imports
        exclude: tests/fixtures

-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
