pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -ex
    docker network create -d bridge derex
    DOCKER_COMPOSE="docker-compose -f derex/runner/templates/docker-compose-services.yml -f derex/runner/templates/docker-compose-edx.yml"
    ${DOCKER_COMPOSE} up -d
    ${DOCKER_COMPOSE} logs
    sleep 5
    ${DOCKER_COMPOSE} logs
    sleep 5
    ${DOCKER_COMPOSE} logs
  displayName: 'Start daemons'

- script: docker run --network derex --rm derex/openedx-ironwood:latest restore_dump.py
  displayName: 'Prime mysql database'

- script: docker run --network derex -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf -p 80:80 -d --rm nginx:1.17.0-alpine
  displayName: 'Start nginx'

- script: |
    echo 127.0.0.1 localhost studio.localhost | sudo tee -a /etc/hosts
    sleep 3  # Give the services a little time to start up
  displayName: Add studio.localhost to /etc/hosts

- script: curl http://localhost/
  displayName: 'Curl the LMS'

- script: curl http://studio.localhost/
  displayName: 'Curl the CMS'
