schedules:
  - cron: "30 06 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

stages:
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/test.yml
  - template: azure-pipelines/push.yml

variables:
  - name: CACHE_KEY_BASE # Increment this value to reset the images cache
    value: 22
  - name: CACHE_KEY_FILES
    value: $(System.DefaultWorkingDirectory)/docker-definition/**/*
  - name: CACHE_KEY_IMAGES
    value: BASE_SEED=$(CACHE_KEY_BASE) | $(CACHE_KEY_FILES)
  - name: IMAGE_CACHE_PATH
    value: $(Pipeline.Workspace)/image_cache
  - name: SENTINEL_CACHE_PATH
    value: $(Pipeline.Workspace)/sentinel_cache
  - name: UBUNTU_VERSION
    value: ubuntu-latest

  - name: needs_build
    value: "false"
