schedules:
- cron: "30 06 * * *"
  displayName: Daily build
  branches:
    include:
      - master
  always: true

stages:
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/test.yml
  - template: azure-pipelines/push.yml
