schedules:
- cron: "30 06 * * *"
  displayName: Daily build
  branches:
    include:
      - master
  always: true

stages:
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/test.yml
  - template: azure-pipelines/push.yml

variables:
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_COMMAND
    value: docker buildx build docker-definition
  - name: CACHE_KEY_BASE  # Increment this value to reset the layers cache and the image cache
    value: 17
  - name: LAYERS_CACHE_DIR
    value: '$(Pipeline.Workspace)/layers_cache'
  - name: CACHE_KEY_FALLBACK
    value: '"CACHE_KEY_BASE=$(CACHE_KEY_BASE)" | "$(Agent.OS) $(Agent.JobName)"'
  - name: CACHE_KEY_FILES
    value: $(System.DefaultWorkingDirectory)/docker-definition/*
  - name: CACHE_KEY_IMAGES
    value: BASE_SEED=$(CACHE_KEY_BASE) | $(CACHE_KEY_FILES)
  - name: CACHE_KEY_EXACT
    value: $(CACHE_KEY_FALLBACK) | $(CACHE_KEY_FILES)
  - name: SENTINEL_CACHE_PATH
    value: $(Pipeline.Workspace)/sentinel_cache
  - name: IMAGE_CACHE_PATH
    value: $(Pipeline.Workspace)/image_cache
  # This is the key used by images cache and images cache sentinel
  # It does not include $(CACHE_KEY_FILES) as it should, because
  # if it does Azure can't find the files.
  - name: IMAGES_CACHE_KEY
    value: SENTINEL=1 | $(DOCKER_IMAGES_SLUG)
  - name: needs_build
    value: "false"
