pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker-compose -f first_tests/docker-compose.yml pull
  displayName: 'Pull docker images'

- script: |
    set -x
    cd first_tests
    docker-compose up -d mysql
    sleep 10
    docker-compose exec -T mysql mysql -u root -psecret -e 'CREATE DATABASE IF NOT EXISTS myedx'
    docker-compose exec -T mysql mysql -u root -psecret -e 'SHOW DATABASES'
    docker-compose up -d
    docker-compose run lms ./manage.py lms --settings=derex.base migrate
    #docker-compose run cms ./manage.py cms --settings=derex.base migrate
  displayName: 'Run migrations and start Open edX services'

- script: docker-compose exec mysql mysqldump -psecret myedx |xz -9 -c - >  basedump.sql.xz
  displayName: 'Dump mysql database'

- script: curl http://localhost:8000/
  displayName: 'Run a curl'

- script: docker-compose -f first_tests/docker-compose.yml logs
  displayName: 'Show docker logs'
