pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    pip3 install -U pip setuptools
    pip3 install -r requirements_dev.txt
    pip3 install -r requirements.txt .
    pip3 install git+https://github.com/Abstract-Tech/pytest-azurepipelines.git
  displayName: 'Install derex.runner'

- script: docker pull derex/openedx-ironwood:latest &
  displayName: 'Pull edX image in background'

- script: |
    set -ex
    cd tests
    pytest --ignore-docstrings |grep -v codecoveragetool=Cobertura
  displayName: 'Run python tests'

- script: |
    npm install juice
    # Azure pipelines strips style sheets but leaves styles in place.
    # juice can embed the styles in the HTML for us and present a much better
    # view in the coverage results tab.
    for filename in tests/htmlcov/*.html; do $(npm bin)/juice $filename $filename; done
    echo "##vso[codecoverage.publish codecoveragetool=Cobertura;summaryfile=$(pwd)/tests/test-cov.xml;reportdirectory=${PWD}/tests/htmlcov;]"
  displayName: Fix coverage result and publish it
  condition: succeededOrFailed()

- script: |
    set -ex
    export DEREX_ADMIN_SERVICES=False
    ddc up -d
    ddc logs
    sleep 5
    ddc logs
  displayName: 'Start service daemons'

- script: |
    docker-compose --project-name ironwood -f derex/runner/docker_compose_files/edx.yml up -d
  displayName: 'Start edX daemons'

- script: docker run --network derex --rm derex/openedx-ironwood:latest restore_dump.py
  displayName: 'Prime mysql database'

- script: docker run --network derex -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf -p 80:80 -d --rm nginx:1.17.0-alpine
  displayName: 'Start nginx'

- script: |
    ddc logs
    echo 127.0.0.1 localhost studio.localhost | sudo tee -a /etc/hosts
    sleep 3  # Give the services a little time to start up
  displayName: Add studio.localhost to /etc/hosts

- script: curl http://localhost/
  displayName: 'Curl the LMS'

- script: curl http://studio.localhost/
  displayName: 'Curl the CMS'
