project_name: ironwood-complete
openedx_version: ironwood
collect_assets: true
materialize_derex_settings: false
variables:
  lms_test_dict:
    default: { "foo": "bar" }
    production: { "foo": "baz" }
