# Services to monitor/inspect Open edX
version: "3"
services:
  flower:
    image: derex/openedx-ironwood:latest
    command: sh -c 'pip install flower; flower --broker=$$(python -c "from django.conf import settings; print(settings.BROKER_URL)") --port=5555'
    ports:
      - 127.0.0.1:5555:5555
    container_name: derex_flower
    depends_on:
      - rabbitmq

  adminer:
    image: adminer:4.7.1
    ports:
      - 127.0.0.1:4400:8080
    depends_on:
      - mysql

  portainer:
    image: portainer/portainer:1.21.0
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer

volumes:
  portainer_data:
