version: "3"
services:
  mongodb:
    image: mongo:3.2.21
    container_name: mongodb
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger --wiredTigerEngineConfigString="cache_size=${MONGO_CACHE_MB:-200}M"
    volumes:
      - derex_mongodb:/data/db

  mysql:
    image: mysql:5.6.36
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - derex_mysql:/var/lib/mysql

  mailslurper:
    image: marcopas/docker-mailslurper
    # Something needs to prime this with
    # docker-compose -f derex/runner/templates/docker-compose.yml exec mysql /usr/bin/mysql -psecret -e "$(cat derex/runner/templates/mailslurper.sql)"
    container_name: smtp
    ports:
      - 4300:4300
      - 4301:4301
    volumes:
      - ./mailslurper.json:/opt/mailslurper/config.json
    depends_on:
      - mysql

  adminer:
    image: adminer:4.7.1
    ports:
      - 4400:4400

volumes:
  derex_mongodb:
  derex_mysql:

networks:
  default:
    external:
      name: derex
