from kombu.utils.functional import maybe_list


CELERY_BROKER_VHOST = "{}_edxqueue".format(DEREX_PROJECT)

CELERY_BROKER_TRANSPORT = "amqp"
CELERY_BROKER_HOSTNAME = "rabbitmq"
CELERY_BROKER_USER = "guest"
CELERY_BROKER_PASSWORD = "guest"
BROKER_URL = "{0}://{1}:{2}@{3}/{4}".format(
    CELERY_BROKER_TRANSPORT,
    CELERY_BROKER_USER,
    CELERY_BROKER_PASSWORD,
    CELERY_BROKER_HOSTNAME,
    CELERY_BROKER_VHOST,
)
CELERY_RESULT_BACKEND = "cache+memcached://memcached:11211/"

CELERY_IMPORTS = locals().get("CELERY_IMPORTS", [])
# XXX for some reason celery is not registering the bookmarks app
CELERY_IMPORTS = list(maybe_list(CELERY_IMPORTS)) + [
    "openedx.core.djangoapps.bookmarks.tasks",
    "openedx.core.djangoapps.content.course_overviews.tasks",
]
CELERYBEAT_SCHEDULE = {}

CELERY_ROUTES = "{}.celery.Router".format(SERVICE_VARIANT)
CELERY_QUEUES = {"openedx.lms.default": {}, "openedx.cms.default": {}}

CELERY_DEFAULT_EXCHANGE = "openedx.{}".format(SERVICE_VARIANT)
CELERY_DEFAULT_QUEUE = "{}.default".format(CELERY_DEFAULT_EXCHANGE)
HIGH_PRIORITY_QUEUE = CELERY_DEFAULT_QUEUE
DEFAULT_PRIORITY_QUEUE = CELERY_DEFAULT_QUEUE
HIGH_MEM_QUEUE = CELERY_DEFAULT_QUEUE

CELERY_DEFAULT_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE

ACE_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
BULK_EMAIL_ROUTING_KEY = HIGH_PRIORITY_QUEUE
BULK_EMAIL_ROUTING_KEY_SMALL_JOBS = DEFAULT_PRIORITY_QUEUE
COURSEGRAPH_JOB_QUEUE = DEFAULT_PRIORITY_QUEUE
CREDENTIALS_GENERATION_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
GRADES_DOWNLOAD_ROUTING_KEY = HIGH_MEM_QUEUE
POLICY_CHANGE_GRADES_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
PROGRAM_CERTIFICATES_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
RECALCULATE_GRADES_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
SCRAPE_YOUTUBE_THUMBNAILS_JOB_QUEUE = DEFAULT_PRIORITY_QUEUE
SOFTWARE_SECURE_VERIFICATION_ROUTING_KEY = DEFAULT_PRIORITY_QUEUE
UPDATE_SEARCH_INDEX_JOB_QUEUE = DEFAULT_PRIORITY_QUEUE
VIDEO_TRANSCRIPT_MIGRATIONS_JOB_QUEUE = DEFAULT_PRIORITY_QUEUE
