FEATURES.update(
    {
        "ALLOW_ALL_ADVANCED_COMPONENTS": True,
        "ALLOW_COURSE_STAFF_GRADE_DOWNLOADS": True,
        "ALWAYS_REDIRECT_HOMEPAGE_TO_DASHBOARD_FOR_AUTHENTICATED_USER": False,
        "CERTIFICATES_ENABLED": True,
        "CERTIFICATES_HTML_VIEW": True,
        "CERTIFICATES_INSTRUCTOR_GENERATION": True,
        "DISABLE_STUDIO_SSO_OVER_LMS": False,
        "ENABLE_COMBINED_LOGIN_REGISTRATION": True,
        "ENABLE_COMBINED_LOGIN_REGISTRATION_FOOTER": False,
        "ENABLE_CORS_HEADERS": True,
        "ENABLE_DISCUSSION_SERVICE": True,
        "ENABLE_GRADE_DOWNLOADS": True,
        "ENABLE_OAUTH2_PROVIDER": True,
        "ENABLE_SPECIAL_EXAMS": True,
        "ENABLE_SYSADMIN_DASHBOARD": True,
    }
)
