MEDIA_ROOT = "/openedx/media"
VIDEO_TRANSCRIPTS_SETTINGS["location"] = MEDIA_ROOT
VIDEO_IMAGE_SETTINGS["STORAGE_KWARGS"]["location"] = MEDIA_ROOT
PROFILE_IMAGE_BACKEND["options"]["location"] = MEDIA_ROOT
