#!/bin/sh
set -e

SERVICE_VARIANT=lms python manage.py lms compilemessages
SERVICE_VARIANT=cms python manage.py cms compilemessages
SERVICE_VARIANT=lms python manage.py lms compilejsi18n
SERVICE_VARIANT=cms python manage.py cms compilejsi18n

sh -c 'mkdir -p /openedx/staticfiles/js/i18n/; cp -rf /openedx/edx-platform/lms/static/js/i18n/ /openedx/staticfiles/js/i18n/'
sh -c 'apk add gzip; gzip -rkf /openedx/staticfiles/js/i18n/*/*.js; apk del gzip'
sh -c 'apk add brotli; brotli -f /openedx/staticfiles/js/i18n/*/*.js; apk del brotli'
