version: "3"
services:
  mongodb:
    image: mongo:3.2.16
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    volumes:
      - mongo:/data/db

  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  elasticsearch:
    image: elasticsearch:1.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=openedx"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  lms:
    image: derex/openedx-ironwood-tutor:cf05a11af5
    command: sh -c "gunicorn --name $${SERVICE_VARIANT} --bind=0.0.0.0:8000 --max-requests=1000 wsgi:application"
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.derex.base
      SETTINGS: derex.base
    ports:
      - "8000:8000"
    volumes:
      - ./config/:/openedx/edx-platform/lms/envs/derex
      - openedx_data:/openedx/data
    depends_on:
      - elasticsearch
      - mongodb
      - mysql

volumes:
  mongo:
  mysql:
  elasticsearch:
  openedx_data:
