name: Build
on: [push]

env:
  CACHE_KEY_BASE: 22 # Increment this value to reset the images cache
  CACHE_KEY_FILES: $GITHUB_WORKSPACE/docker-definition/**/*
  CACHE_KEY_IMAGES: BASE_SEED=$CACHE_KEY_BASE | $CACHE_KEY_FILES
  IMAGE_CACHE_PATH: $GITHUB_WORKSPACE/image_cache
  SENTINEL_CACHE_PATH: $GITHUB_WORKSPACE/sentinel_cache

jobs:
  juniper:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_IMAGES_SLUG: juniper
    steps:
      - name: Resolve Sentinel cache
        id: cache-juniper
        uses: action/cache@v3
        with:
          path: $(SENTINEL_CACHE_PATH)
          key: SENTINEL=1 | $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)

  koa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_IMAGES_SLUG: koa
    steps:
      - name: Resolve Sentinel cache
        id: cache-koa
        uses: action/cache@v3
        with:
          path: $(SENTINEL_CACHE_PATH)
          key: SENTINEL=1 | $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)
  lilac:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_IMAGES_SLUG: lilac
    steps:
      - name: Resolve Sentinel cache
        id: cache-lilac
        uses: action/cache@v3
        with:
          path: $(SENTINEL_CACHE_PATH)
          key: SENTINEL=1 | $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)