name: Build
on: [push]

env:
  CACHE_KEY_BASE: 22 # Increment this value to reset the images cache
#  CACHE_KEY_FILES: ${{ System.DefaultWorkingDirectory }}/docker-definition/**/*
#  CACHE_KEY_IMAGES: BASE_SEED=${{ CACHE_KEY_BASE }} | ${{ CACHE_KEY_FILES }}
#  IMAGE_CACHE_PATH: ${{ Pipeline.Workspace }}/image_cache
#  SENTINEL_CACHE_PATH: ${{ Pipeline.Workspace }}/sentinel_cache

jobs:
  Juniper:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: pwd

  Koa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

  Lilac:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
