name: on_push

on:
  push

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  push:
    uses: ./.github/workflows/push.yml
    needs: [build, test]