name: Build
on:
  push

env:
  PYTEST_ADDOPTS: --cov=derex --cov-report xml --cov-report html --cov-report term --cov-report term-missing --cov-branch --black
  AS_PYTHON_PACKAGE: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        OPENEDX_RELEASE: [ juniper,koa,lilac ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: $GITHUB_WORKSPACE/.cache/pip
          key: pipcache | requirements_dev.txt
          restore-keys: pipcache

      - name: Install derex.runner
        if: env.AS_PYTHON_PACKAGE == 'false' && env.NEEDS_BUILD != 'false'
        run: |
          pip3 install --cache-dir $GITHUB_WORKSPACE/.cache/pip -U pip setuptools
          pip3 install --cache-dir $GITHUB_WORKSPACE/.cache/pip -r requirements_dev.txt -e .

      - name: Install derex.runner as python package
        if: env.AS_PYTHON_PACKAGE != 'false' && env.NEEDS_BUILD != 'false'
        run: |
          pip3 install --cache-dir $GITHUB_WORKSPACE/.cache/pip -U pip setuptools
          pip3 install --cache-dir $GITHUB_WORKSPACE/.cache/pip .

      - name: Build linux binary with pyinstaller
        run: |
          pip install pyinstaller
          make executable

      - name: Test pyinstaller created linux binary
        run: |
          set -ex
          ./bundle/dist/derex
          ./bundle/dist/ddc-services ps
          cd examples/${{ matrix.OPENEDX_RELEASE }}/minimal
          ../../../bundle/dist/ddc-project config

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: LinuxBinary
          path: ./bundle/dist/

      - name: Build macOS binary with pyinstaller
        run: |
          pip install pyinstaller scrypt
          # The Openssl version on MacOS 10.14 does not support scrypt
          # so we pip install it and leave a trace to pyinstaller to pick it up
          echo -e  "\nimport scrypt" >> bundle/executable.py
          make executable

      - name: Test pyinstaller created macOS binary
        run: |
          set -ex
          ./bundle/dist/derex --help
          ./bundle/dist/ddc-services --help
          cd examples/${{ matrix.OPENEDX_RELEASE }}/minimal
          ../../../bundle/dist/ddc-project config

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: MacOSBinary
          path: ./bundle/dist/

      - name: Run python tests
        run: |
          set -ex
          set -o pipefail
          pip3 --cache-dir $GITHUB_WORKSPACE/.cache/pip install scrypt
          cd tests
          pytest -m "not slowtest" | grep -v codecoveragetool=Cobertura
          
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: fasttests_coverage
          path: $GITHUB_WORKSPACE/tests/.coverage

      - name: Docker images cache
        if: steps.cache-sentinel.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: $IMAGE_CACHE_PATH
          key: BASE_SEED=$CACHE_KEY_BASE | ${{ matrix.OPENEDX_RELEASE }} | $CACHE_KEY_IMAGES
          restore-keys: BASE_SEED=$CACHE_KEY_BASE | ${{ matrix.OPENEDX_RELEASE }}

      - name: Load images
        if: steps.cache-sentinel.outputs.cache-hit != 'true'
        run: |
          [ -d $IMAGE_CACHE_PATH ] || exit 0
          ls -l $IMAGE_CACHE_PATH
          docker images
          set -euxo pipefail
          cat $IMAGE_CACHE_PATH/edx-${{ matrix.OPENEDX_RELEASE }}.tar.xz | unxz | docker load
          docker images

      - name: Provision and test services
        run: |
          ddc-services config
          ddc-services pull
          set -ex
          export DEREX_ADMIN_SERVICES=False
          ddc-services up -d
          # Give it some seconds to boot
          sleep 15
          derex reset-mailslurper
          set -o pipefail
          cd tests
          rm -r $GITHUB_WORKSPACE/tests/.coverage
          pytest -m "slowtest" | grep -v codecoveragetool=Cobertura

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: slowtests_coverage
          path: $GITHUB_WORKSPACE/tests/.coverage