steps:
  # Sentinel cache: if this one hits, it means the image cache will hit too
  # We don't use the image cache for performance reasons
  - task: Cache@2
    inputs:
      key: SENTINEL=1 | $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)
      path: $(SENTINEL_CACHE_PATH)
      cacheHitVar: "ImagesSentinelHit"
    displayName: "Docker images sentinel cache"

  - template: load_images.yml
    parameters:
      DOCKER_IMAGES_SLUG: $(DOCKER_IMAGES_SLUG)
      CONDITION: ne(variables.ImagesSentinelHit, 'true')

  - script: echo '##vso[task.setvariable variable=needs_build]true'
    condition: ne(variables.ImagesSentinelHit, 'true')
    displayName: "Set needs_build pipeline variable"

  - script: df -h; time sudo rm -rf /var/cache/apt/archives /opt/ghc; df -h
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: "Remove Haskell compiler and cached apt archives to save disk space"

  - script: |
      if [ "$TRANSIFEX_USERNAME" == '$(TRANSIFEX_USERNAME)' ] || [ "$TRANSIFEX_PASSWORD" == '$(TRANSIFEX_PASSWORD)' ]; then
          echo "Transifex credentials unset. Building without translations."
          exit 0
      fi
      printf '[https://www.transifex.com]\nhostname=https://www.transifex.com\nusername=%s\npassword=%s\n' "${TRANSIFEX_USERNAME}" "${TRANSIFEX_PASSWORD}" > $HOME/.transifexrc
      ls -l $HOME/.transifexrc
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: "Prepare Transifex credentials"
    env:
      TRANSIFEX_USERNAME: $(TRANSIFEX_USERNAME)
      TRANSIFEX_PASSWORD: $(TRANSIFEX_PASSWORD)

  - script: |
      images=$(docker images|grep -v '<none>'|grep derex|awk '{print $1 ":" $2}')
      CACHE_FROM_OPTS=""
      if [ -d "$(IMAGE_CACHE_PATH)" ]; then
        echo "Will use cached layers from images $images"
        for image in $images; do
          CACHE_FROM_OPTS="${CACHE_FROM_OPTS} --cache-from=$image"
        done
      else
        mkdir $(IMAGE_CACHE_PATH)
      fi
      echo "##vso[task.setvariable variable=CACHE_FROM_OPTS]${CACHE_FROM_OPTS}"
      mkdir $(SENTINEL_CACHE_PATH)
      cp -r $(CACHE_KEY_FILES) $(SENTINEL_CACHE_PATH)
      # We save the sha of the repo that built this image, so that we can push
      # it only in a build of the same commit, after tests are passed
      git rev-parse --verify HEAD > $(SENTINEL_CACHE_PATH)/built_version
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: "Setup docker images cache"

  - script: |
      set -ex
      sudo apt-get remove moby-cli -y
      curl -fsSL https://get.docker.com |sudo bash
      sudo mv /etc/docker/daemon.json /etc/docker/daemon.json.orig
      sudo cat /etc/docker/daemon.json.orig|jq '. + {experimental: true}' |sudo tee /etc/docker/daemon.json
      sudo systemctl restart docker.service
      docker version
      docker buildx create --use
      docker images
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Replace Microsoft docker with upsream docker and create build context

  - script: sudo apt-get install pixz -y
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Install pixz

  - template: prepare.yml
    parameters:
      CONDITION: "ne(variables.needs_build, 'false')"

  - script: derex build openedx --docker-opts "${CACHE_FROM_OPTS} --cache-to=type=inline -o type=docker --build-arg TRANSLATIONS_CACHEBURST=${date +%d%m%y}" --target=nostatic $(DOCKER_IMAGES_SLUG)
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Build nostatic image

  - script: derex build openedx --docker-opts "--cache-to=type=inline -o type=docker --build-arg TRANSLATIONS_CACHEBURST=${date +%d%m%y}" --target=dev $(DOCKER_IMAGES_SLUG)
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Build dev image

  - script: |
      docker images
      derex build openedx --docker-opts "${CACHE_FROM_OPTS} --output type=docker,name={docker_image_prefix}-{target} --build-arg TRANSLATIONS_CACHEBURST=${date +%d%m%y}" --target=translations $(DOCKER_IMAGES_SLUG)
      docker images
      docker run --rm derex/openedx-${DOCKER_IMAGES_SLUG}-translations:$(grep __version__ derex/runner/__init__.py |sed 's/[^"]*"//;s/"//') sh -c "i18n_tool validate || (find conf|grep prob; find conf|grep prob|xargs cat; false)" ||
        echo "##vso[task.logissue type=error]Problems with translations found"
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Check translations

  - script: |
      set -euxo pipefail;
      docker save \
        $(derex build openedx --only-print-image-name -t nostatic $(DOCKER_IMAGES_SLUG)) \
        $(derex build openedx --only-print-image-name -t dev $(DOCKER_IMAGES_SLUG)) \
        | pixz -0 > $(IMAGE_CACHE_PATH)/edx-$(DOCKER_IMAGES_SLUG).tar.xz
    condition: and(succeeded(), ne(variables.needs_build, 'false'))
    displayName: Save images
