stages:
  - stage: Build
    variables:
      - group: Transifex credentials

    jobs:
      - job: hawthorn
        timeoutInMinutes: 180
        pool:
          vmImage: "ubuntu-18.04"
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: hawthorn
        steps:
          - template: build_single_version.yml

      - job: ironwood
        timeoutInMinutes: 180
        pool:
          vmImage: "ubuntu-18.04"

        variables:
          - name: DOCKER_IMAGES_SLUG
            value: ironwood
        steps:
          - template: build_single_version.yml

      - job: juniper
        timeoutInMinutes: 180
        pool:
          vmImage: "ubuntu-18.04"
        continueOnError: true # bad translations currently cause errors
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: juniper
        steps:
          - template: build_single_version.yml
