stages:
  - stage: Build
    variables:
      - group: Transifex credentials

    jobs:
      - job: ironwood
        timeoutInMinutes: 180
        pool:
          vmImage: $(UBUNTU_VERSION)

        variables:
          - name: DOCKER_IMAGES_SLUG
            value: ironwood
        steps:
          - template: build_single_version.yml

      - job: juniper
        timeoutInMinutes: 180
        pool:
          vmImage: $(UBUNTU_VERSION)
        continueOnError: true # bad translations currently cause errors
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: juniper
        steps:
          - template: build_single_version.yml

      - job: koa
        timeoutInMinutes: 180
        pool:
          vmImage: $(UBUNTU_VERSION)
        continueOnError: true # bad translations currently cause errors
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: koa
        steps:
          - template: build_single_version.yml

      - job: lilac
        timeoutInMinutes: 180
        pool:
          vmImage: $(UBUNTU_VERSION)
        continueOnError: true # bad translations currently cause errors
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: lilac
        steps:
          - template: build_single_version.yml
