steps:
  # Sentinel cache: if this one hits, it means the image cache will hit too
  # We don't use the image cache for performance reasons
  - task: Cache@2
    inputs:
      key: SENTINEL=1 | $(CACHE_KEY_IMAGES)
      path: $(SENTINEL_CACHE_PATH)
      cacheHitVar: 'ImagesSentinelHit'
    displayName: 'Docker images sentinel cache'

  - task: Cache@2
    inputs:
      key: $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)
      path: $(IMAGE_CACHE_PATH)
      cacheHitVar: 'ImagesHit'
    displayName: 'Docker images cache'

  - script: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    displayName: 'Log into docker registry'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)

  - script: |
      docker images
      cat $(IMAGE_CACHE_PATH)/edx-$(DOCKER_IMAGES_SLUG).tar.xz | unxz | docker load
      docker images
      docker run --rm derex/edx-$(DOCKER_IMAGES_SLUG)-dev ls /
      docker run --rm derex/edx-$(DOCKER_IMAGES_SLUG)-nostatic ls /
      docker push derex/edx-$(DOCKER_IMAGES_SLUG)-dev
      docker push derex/edx-$(DOCKER_IMAGES_SLUG)-nostatic
    displayName: Try to load docker images
