stages:
- stage: Build
  variables:
    - group: Docker credentials
    #- group: Transifex credentials
    - name: DOCKER_BUILDKIT
      value: '1'
    - name: DOCKER_CLI_EXPERIMENTAL
      value: enabled
    - name: DOCKER_COMMAND
      value: docker buildx build docker-definition
    - name: CACHE_KEY_BASE  # Increment this value to reset the layers cache
      value: 1
    - name: LAYERS_CACHE_DIR
      value: '$(Pipeline.Workspace)/layers_cache'
    - name: CACHE_KEY_FALLBACK
      value: '"CACHE_KEY_BASE=$(CACHE_KEY_BASE)" | "$(Agent.OS) $(Agent.JobName)"'
    - name: CACHE_KEY_FILES
      value: $(System.DefaultWorkingDirectory)/docker-definition/*
    - name: CACHE_KEY_EXACT
      value: $(CACHE_KEY_FALLBACK) | $(CACHE_KEY_FILES)
    - name: SENTINEL_CACHE_PATH
      value: $(Pipeline.Workspace)/sentinel_cache
    - name: IMAGE_CACHE_PATH
      value: $(Pipeline.Workspace)/image_cache

  jobs:
  - job: Build_hawthorn_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      - name: DOCKER_IMAGES_SLUG
        value: hawthorn
      - name: DOCKER_OPTS
        value: --build-arg PYTHON_VERSION=2.7 --build-arg EDX_PLATFORM_VERSION=open-release/$(DOCKER_IMAGES_SLUG).master
    steps:
      - template: build_single_version.yml

  - job: Build_ironwood_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      - name: DOCKER_IMAGES_SLUG
        value: ironwood
      - name: DOCKER_OPTS
        value: --build-arg PYTHON_VERSION=2.7 --build-arg EDX_PLATFORM_VERSION=open-release/$(DOCKER_IMAGES_SLUG).master
    steps:
      - template: build_single_version.yml


  - job: Build_juniper_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      - name: DOCKER_IMAGES_SLUG
        value: juniper
      - name: DOCKER_OPTS
        value:
    steps:
      - template: build_single_version.yml
