steps:
  # Sentinel cache: if this one hits, it means the image cache will hit too
  # We don't use the image cache for performance reasons
  - task: Cache@2
    inputs:
      key: SENTINEL=1 | $(CACHE_KEY_IMAGES)
      path: $(SENTINEL_CACHE_PATH)
      cacheHitVar: 'ImagesSentinelHit'
    displayName: 'Docker images sentinel cache'

  - script: echo  "##vso[task.setvariable variable=needs_build]true"
    condition: ne(variables.ImagesSentinelHit, 'true')
    displayName: 'Set needs_build pipeline variable'

  - script: |
      if [ -z "$TRANSIFEX_USERNAME" ] || [ -z "$TRANSIFEX_PASSWORD" ]; then
          echo "Transifex credentials unset. Building without translations."
          exit 0
      fi
      printf '[https://www.transifex.com]\nhostname=https://www.transifex.com\nusername=%s\npassword=%s\n' "${TRANSIFEX_USERNAME}" "${TRANSIFEX_PASSWORD}" > $HOME/.transifexrc
      ls -l $HOME/.transifexrc
    condition: eq(variables.needs_build, 'true')
    displayName: 'Prepare Transifex credentials'
    env:
      TRANSIFEX_USERNAME: $(TRANSIFEX_USERNAME)
      TRANSIFEX_PASSWORD: $(TRANSIFEX_PASSWORD)

  - task: Cache@2
    inputs:
      key: $(DOCKER_IMAGES_SLUG) | $(CACHE_KEY_IMAGES)
      path: $(IMAGE_CACHE_PATH)
      cacheHitVar: 'ImagesHit'
    condition: eq(variables.needs_build, 'true')
    displayName: 'Docker images cache'

  # restore the docker cache based on the Dockerfile
  - task: Cache@2
    inputs:
      key: $(CACHE_KEY_EXACT)
      path: '$(LAYERS_CACHE_DIR)'
      cacheHitVar: 'BuildKitLayersHit'
      restoreKeys: $(CACHE_KEY_FALLBACK)
    condition: eq(variables.needs_build, 'true')
    displayName: 'Docker layers cache'

  - script: |
      if [ -d "$(LAYERS_CACHE_DIR)" ]; then
        echo "Will use cached layers from $(LAYERS_CACHE_DIR)"
        find $(LAYERS_CACHE_DIR)
        DOCKER_OPTS="$DOCKER_OPTS --cache-from=type=local,src=$(LAYERS_CACHE_DIR)"
      else
        mkdir ${LAYERS_CACHE_DIR}
      fi
      if [ "$(BuildKitLayersHit)" != "true" ]; then
        echo "Will store cached layers to $(LAYERS_CACHE_DIR)"
        DOCKER_OPTS="$DOCKER_OPTS --cache-to=type=local,dest=$(LAYERS_CACHE_DIR)"
      fi
      echo  "##vso[task.setvariable variable=DOCKER_OPTS]${DOCKER_OPTS}"
      mkdir $(SENTINEL_CACHE_PATH)
      mkdir $(IMAGE_CACHE_PATH)
      cp -r $(CACHE_KEY_FILES) $(SENTINEL_CACHE_PATH)
    condition: eq(variables.needs_build, 'true')
    displayName: 'Setup docker layers cache'

  - script: |
      set -ex
      sudo apt-get remove moby-cli -y
      curl -fsSL https://get.docker.com |sudo bash
      sudo mv /etc/docker/daemon.json /etc/docker/daemon.json.orig
      sudo cat /etc/docker/daemon.json.orig|jq '. + {experimental: true}' |sudo tee /etc/docker/daemon.json
      sudo systemctl restart docker.service
      docker version
      docker buildx create --use
    condition: eq(variables.needs_build, 'true')
    displayName: Replace Microsoft docker with upsream docker and create build context

  - script: ${DOCKER_COMMAND} ${DOCKER_OPTS} --load -t derex/edx-${DOCKER_IMAGES_SLUG}-nostatic --target=nostatic --secret id=transifex,src=$HOME/.transifexrc
    condition: eq(variables.needs_build, 'true')
    displayName: Build nostatic image

  - script: ${DOCKER_COMMAND} ${DOCKER_OPTS} --load -t derex/edx-${DOCKER_IMAGES_SLUG}-dev --target=dev --secret id=transifex,src=$HOME/.transifexrc
    condition: eq(variables.needs_build, 'true')
    displayName: Build dev image

  - script: sudo apt-get install pxz -y
    condition: eq(variables.needs_build, 'true')
    displayName: Install pxz

  - script: docker save derex/edx-${DOCKER_IMAGES_SLUG}-dev derex/edx-${DOCKER_IMAGES_SLUG}-nostatic | pxz -0 -z > $(IMAGE_CACHE_PATH)/edx-$(DOCKER_IMAGES_SLUG).tar.xz
    condition: eq(variables.needs_build, 'true')
    displayName: Save docker images into image cache
