stages:
- stage: Build
  variables:
  - group: Transifex credentials

  jobs:
  - job: Build_hawthorn_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      - name: DOCKER_IMAGES_SLUG
        value: hawthorn
      - name: DOCKER_OPTS
        value: --build-arg PYTHON_VERSION=2.7 --build-arg EDX_PLATFORM_VERSION=open-release/$(DOCKER_IMAGES_SLUG).master
    steps:
      - template: build_single_version.yml

  - job: Build_ironwood_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      - name: DOCKER_IMAGES_SLUG
        value: ironwood
      - name: DOCKER_OPTS
        value: --build-arg PYTHON_VERSION=2.7 --build-arg EDX_PLATFORM_VERSION=open-release/$(DOCKER_IMAGES_SLUG).master
    steps:
      - template: build_single_version.yml


  - job: Build_juniper_image
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'
    continueOnError: true  # bad translations currently cause errors
    variables:
      - name: DOCKER_IMAGES_SLUG
        value: juniper
      - name: DOCKER_OPTS
        value:
    steps:
      - template: build_single_version.yml
