steps:
  - download: current
    artifact: $(DOCKER_IMAGES_SLUG)_image_dev

  - download: current
    artifact: $(DOCKER_IMAGES_SLUG)_image_nostatic

  - script: |
      docker image import $(Pipeline.Workspace)/edx-$(DOCKER_IMAGES_SLUG)-dev.tar derex/edx-$(DOCKER_IMAGES_SLUG)-dev
    displayName: 'Push $(DOCKER_IMAGES_SLUG) dev image'

  - script: |
      docker image import $(Pipeline.Workspace)/edx-$(DOCKER_IMAGES_SLUG)-dev.tar derex/edx-$(DOCKER_IMAGES_SLUG)-nostatic
    displayName: 'Push $(DOCKER_IMAGES_SLUG) nostatic image'
