parameters:
  - name: DOCKER_IMAGES_SLUG
    type: string
    default: ironwood

steps:
  - download: current
    artifact: ${{ parameters.DOCKER_IMAGES_SLUG }}_image_dev

  - download: current
    artifact: ${{ parameters.DOCKER_IMAGES_SLUG }}_image_nostatic

  - script: |
      docker image import $(Pipeline.Workspace)/${{ parameters.DOCKER_IMAGES_SLUG }}_image_dev/edx-${{ parameters.DOCKER_IMAGES_SLUG }}-dev.tar derex/edx-${{ parameters.DOCKER_IMAGES_SLUG }}-dev
    displayName: 'Load ${{ parameters.DOCKER_IMAGES_SLUG }} dev image'

  - script: |
      docker image import $(Pipeline.Workspace)/${{ parameters.DOCKER_IMAGES_SLUG }}_image_nostatic/edx-${{ parameters.DOCKER_IMAGES_SLUG }}-nostatic.tar derex/edx-${{ parameters.DOCKER_IMAGES_SLUG }}-nostatic
    displayName: 'Load ${{ parameters.DOCKER_IMAGES_SLUG }} nostatic image'
