parameters:
  - name: DOCKER_IMAGES_SLUG
    type: string
    default: ironwood

steps:
  - task: Cache@2
    inputs:
      key: $(CACHE_KEY_FILES)
      path: $(IMAGE_CACHE_PATH)
      cacheHitVar: 'ImagesHit'
    displayName: 'Docker images cache'

  - script: |
      docker load -i $(IMAGE_CACHE_PATH)/edx-${{ parameters.DOCKER_IMAGES_SLUG }}.tar
    displayName: 'Load ${{ parameters.DOCKER_IMAGES_SLUG }} images'
