parameters:
  - name: DOCKER_IMAGES_SLUG
    type: string
    default: ironwood

steps:
  - task: Cache@2
    inputs:
      key: $(CACHE_KEY_IMAGES)
      path: $(IMAGE_CACHE_PATH)
      cacheHitVar: 'ImagesHit'
    displayName: 'Docker images cache'

  - script: |
      ls -l $(IMAGE_CACHE_PATH)
      cat $(IMAGE_CACHE_PATH)/edx-${{ parameters.DOCKER_IMAGES_SLUG }}.tar.xz | pxz -d | docker load
    displayName: 'Load ${{ parameters.DOCKER_IMAGES_SLUG }} images'
