parameters:
  - name: CONDITION
    type: string
    default: "true"
  - name: AS_PYTHON_PACKAGE
    type: boolean
    default: False

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
    condition: ${{ parameters.CONDITION }}
    displayName: "Use Python 3.7"

  - task: Cache@2
    inputs:
      key: pipcache | requirements_dev.txt
      path: $(Pipeline.Workspace)/.cache/pip
      restoreKeys: |
        pipcache
    condition: ${{ parameters.CONDITION }}
    displayName: Cache pip packages

  - script: |
      pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip -U pip setuptools
      pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip -r requirements_dev.txt -e . git+https://github.com/Abstract-Tech/pytest-azurepipelines.git
    condition: and(${{ parameters.CONDITION }}, eq(${{ parameters.AS_PYTHON_PACKAGE }}, False))
    displayName: "Install derex.runner"

  - script: |
      pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip -U pip setuptools
      pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip . git+https://github.com/Abstract-Tech/pytest-azurepipelines.git
    condition: and(${{ parameters.CONDITION }}, eq(${{ parameters.AS_PYTHON_PACKAGE }}, True))
    displayName: "Install derex.runner as python package"
