steps:
  - script: ddc-services config
    condition: always()
    displayName: "Show ddc-services config"

  - script: ddc-services pull
    displayName: "Pull edX services images"

  - script: |
      set -ex
      export DEREX_ADMIN_SERVICES=False
      ddc-services up -d
      # Give it some seconds to boot
      sleep 15
    displayName: "Start services docker containers"

  - script: |
      set -ex
      derex reset-mailslurper
    displayName: "Prime Mailslurper database"
