stages:
  - stage: Push
    # Check if pushing is needed only on `master` and `build` branches
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/build') ))
    variables:
      - group: Docker credentials
    jobs:
      - job: juniper
        pool:
          vmImage: $(UBUNTU_VERSION)
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: juniper
        steps:
          - template: push_single_version.yml

      - job: koa
        pool:
          vmImage: $(UBUNTU_VERSION)
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: koa
        steps:
          - template: push_single_version.yml

      - job: lilac
        pool:
          vmImage: $(UBUNTU_VERSION)
        variables:
          - name: DOCKER_IMAGES_SLUG
            value: lilac
        steps:
          - template: push_single_version.yml
