stages:

  - stage: Push
    variables:
    - group: Docker credentials
    jobs:

    - job: Push_hawthorn_image
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: hawthorn
      steps:
        - template: push_single_version.yml

    - job: Push_ironwood_image
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: ironwood
      steps:
        - template: push_single_version.yml

    - job: Push_juniper_image
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: hawthorn
      steps:
        - template: push_single_version.yml
