steps:
  - script: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    displayName: 'Log into docker registry'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  - template: load_images.yml

  - script: docker push derex/edx-$(DOCKER_IMAGES_SLUG)-dev
    displayName: 'Push $(DOCKER_IMAGES_SLUG) dev image'

  - script: docker push derex/edx-$(DOCKER_IMAGES_SLUG)-nostatic
    displayName: 'Push $(DOCKER_IMAGES_SLUG) nostatic image'
