stages:

  - stage: Push
    variables:
    - group: Docker credentials
    jobs:

    - job: hawthorn
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: hawthorn
      steps:
        - template: push_single_version.yml

    - job: ironwood
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: ironwood
      steps:
        - template: push_single_version.yml

    - job: juniper
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - name: DOCKER_IMAGES_SLUG
          value: hawthorn
      steps:
        - template: push_single_version.yml

    - job: pypi
      pool:
        vmImage: 'ubuntu-18.04'
      variables:
        - group: Pypi credentials
      steps:
        - template: prepare.yml
        - script: |
            echo -e "[testpypi]\nrepository: https://test.pypi.org/legacy/\nusername: __token__\npassword: ${PYPI_TOKEN}" > ${HOME}/.pypirc
            make dist
            twine upload --verbose --repository=testpypi dist/*
          displayName: Upload to test pypi
          continueOnError: true  # Do not make the build fail because of translation issues
          env:
            PYPI_TOKEN: $(PYPI_TOKEN)
