parameters:
  - name: OS
    type: string
  - name: OPENEDX_RELEASE
    type: string

steps:
  - ${{ if eq(parameters.OS, 'ubuntu') }}:
      - script: |
          pip install pyinstaller
          make executable
        displayName: "Build binary with pyinstaller"

      - script: |
          set -ex
          ./bundle/dist/derex
          ./bundle/dist/ddc-services ps
          cd examples/${{ parameters.OPENEDX_RELEASE }}/minimal
          ../../../bundle/dist/ddc-project config
        displayName: "Test pyinstaller created binary"

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: ./bundle/dist/
          artifactName: LinuxBinary

  - ${{ if eq(parameters.OS, 'macos') }}:
      - script: |
          pip install pyinstaller scrypt
          # The Openssl version on MacOS 10.14 does not support scrypt
          # so we pip install it and leave a trace to pyinstaller to pick it up
          echo -e  "\nimport scrypt" >> bundle/executable.py
          make executable
        displayName: "Build binary with pyinstaller"

      - script: |
          set -ex
          ./bundle/dist/derex --help
          ./bundle/dist/ddc-services --help
          cd examples/${{ parameters.OPENEDX_RELEASE }}/minimal
          ../../../bundle/dist/ddc-project config
        displayName: "Test pyinstaller created binary"

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: ./bundle/dist/
          artifactName: MacOSBinary
