parameters:
  - name: OPENEDX_RELEASE
    type: string

steps:
  - script: |
      pip install pyinstaller
      make executable
    displayName: "Build binary with pyinstaller"

  - script: |
      set -ex
      ./bundle/dist/derex
      ./bundle/dist/ddc-services ps
      cd examples/${{ parameters.OPENEDX_RELEASE }}/minimal
      ../../../bundle/dist/ddc-project config
    displayName: "Test pyinstaller created binary"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: ./bundle/dist/
      artifactName: LinuxBinary
