parameters:
  - name: OPENEDX_RELEASE
    type: string

steps:
  - script: ddc-services pull
    displayName: "Pull edX services images"

  - script: |
      set -ex
      export DEREX_ADMIN_SERVICES=False
      ddc-services up -d
      derex reset-mailslurper
    displayName: "Start service daemons"

  - script: |
      set -ex
      cd examples/${{ parameters.OPENEDX_RELEASE }}/minimal
      docker images
      ddc-project config
      derex mysql reset --force
      derex reset-rabbitmq
      derex create-bucket
    displayName: "Prime Mysql DB"

  - script: |
      set -x
      cd examples/${{ parameters.OPENEDX_RELEASE }}/minimal
      echo 127.0.0.1 localhost flower.minimal.localhost | sudo tee -a /etc/hosts
      ddc-project up -d lms_worker cms_worker flower
      while ! (ddc-project logs cms_worker|grep ready) ; do sleep 1 ; done
      while ! (ddc-project logs lms_worker|grep ready) ; do sleep 1 ; done
      curl -m10 --retry-connrefused --connect-timeout 30 --retry 5 --retry-delay 5 http://flower.minimal.localhost/dashboard?json=1|grep celery@openedx.lms
      curl -m10 --retry-connrefused --connect-timeout 30 --retry 5 --retry-delay 5 http://flower.minimal.localhost/dashboard?json=1|grep celery@openedx.cms
    displayName: "Check flower"
